---
- ansible.builtin.name: Ensure build dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
  tags:
    - plex

- ansible.builtin.name: Add the Apt signing key
  ansible.builtin.apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present
  tags:
    - plex

- ansible.builtin.name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb public main"
    state: present
  tags:
    - plex

- ansible.builtin.name: Add the Plex Media Server package
  ansible.builtin.apt:
    pkg:
      - plexmediaserver
    update_cache: true
  tags:
    - plex

- ansible.builtin.name: Start Plex Media Server
  ansible.builtin.service:
    ansible.builtin.name: plexmediaserver.service
    state: started
    enabled: yes
  tags:
    - plex
